core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from core.views import *


urlpatterns = [
    # Authentication
    path('signup/', user_signup, name='user_signup'),

    path('login/', auth_views.LoginView.as_view(template_name='Auth/login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login'), name='logout'),
    path('profile/change-password/', auth_views.PasswordChangeView.as_view(template_name='Auth/change_password.html'),
         name='change_password'),
    path('profile/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='Auth/success.html'),
         name='password_change_done'),

    path('', dashboard, name='dashboard'),

    # List
    path('users/list/', list_users, name='list_users'),

    # Add/Edit
    path('manage/user/', manage_user, name='add_user'),
    path('manage/user/<uuid:uid>/', manage_user, name='edit_user'),

    # Update My Profile
    path('update/user/<uuid:uid>/', update_profile, name='update_profile'),

    # Delete/Action
    path('users/action/<str:action>/<uuid:uid>/', user_action, name='user_action'),
]

profiles/urls.py
from django.urls import path

from profiles.views import *


urlpatterns = [
    path('manage/profiles/', CreateProfileView.as_view(), name='add_profiles'),
]

profiles/models/contacts.py
import uuid
from django.db import models
from core.models.base import Base
from core.models.regions import State, City
from profiles.models.profiles import Profile


class ContactDetails(Base):
    id = models.CharField(
        primary_key=True,
        max_length=36,
        editable=False,
        default=uuid.uuid4
    )
    profile = models.OneToOneField(
        Profile,
        on_delete=models.CASCADE,
        db_column='profile_id',
    )
    address = models.TextField(
        blank=True,
        null=True
    )
    state = models.ForeignKey(
        State,
        on_delete=models.DO_NOTHING,
        related_name='address_state',
        db_column='state_id',
        null=True,
        blank=True
    )
    district = models.ForeignKey(
        City,
        on_delete=models.DO_NOTHING,
        related_name='address_district',
        db_column='district_id',
        null=True,
        blank=True
    )
    taluka = models.ForeignKey(
        City,
        on_delete=models.DO_NOTHING,
        related_name='address_taluka',
        db_column='taluka_id',
        null=True,
        blank=True
    )
    mobile_no = models.IntegerField(
        blank=True,
        null=True,
    )
    email = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    class Meta:
        db_table = 'contact_details'
        verbose_name_plural = "Contact Details"

    def __str__(self):
        return self.profile.user or self.id

profiles/models/profiles.py
import uuid
from django.db import models

from core.models.regions import State
from core.models.base import User, Base


class TitleTypes(models.IntegerChoices):
    MR = 1, 'MR.'
    MRS = 2, 'Mrs.'
    MS = 3, 'Ms.'
    DR = 4, 'Dr.'


class GenderTypes(models.IntegerChoices):
    MALE = 1, 'Male'
    FEMALE = 2, 'Female'


class MaritalStatusTypes(models.IntegerChoices):
    MARRIED = 1, 'Married'
    UNMARRIED = 2, 'UnMarried'
    SEPARATED = 3, 'Separated'


class CategoryTypes(models.IntegerChoices):
    GENERAL = 1, 'General'
    EWS = 2, 'General(EWS)'
    SC = 3, 'SC'
    SEBC = 4, 'SEBC'
    ST = 5, 'ST'


class CertificateGivenByTypes(models.IntegerChoices):
    MAMALATDAR = 1, 'Mamalatdar'
    TDO = 2, 'T.D.O(Taluka Development Officer)'
    DC = 3, 'District Dy. Director (DC)'
    DO = 4, 'District Social Welfare Officer (DO)'


class Profile(Base):
    id = models.CharField(
        primary_key=True,
        max_length=36,
        editable=False,
        default=uuid.uuid4
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='profiles',
        db_column='user_id',
    )
    unique_id = models.CharField(
        max_length=10,
        unique=True
    )
    title = models.PositiveSmallIntegerField(
        choices=TitleTypes.choices,
        default=TitleTypes.MR,
    )
    surname = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )
    first_name = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )
    father_husband = models.CharField(
        max_length=100,
        null=True,
        blank=True
    )
    mother_name = models.CharField(
        max_length=100,
        null=True,
        blank=True
    )
    gender = models.PositiveSmallIntegerField(
        choices=GenderTypes.choices,
        default=GenderTypes.MALE,
    )
    date_of_birth = models.DateField(
        null=True,
        blank=True
    )
    marital_status = models.PositiveSmallIntegerField(
        choices=MaritalStatusTypes.choices,
        default=MaritalStatusTypes.UNMARRIED,
    )
    category = models.PositiveSmallIntegerField(
        choices=CategoryTypes.choices,
        default=CategoryTypes.GENERAL,
    )
    certificate_no = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )
    certificate_issued_date = models.DateField(
        null=True,
        blank=True
    )
    certificate_issued_from = models.ForeignKey(
        State,
        on_delete=models.DO_NOTHING,
        related_name='certificate_issued_from',
        db_column='certificate_issued_from_id',
        null=True,
        blank=True
    )
    non_creamy_layer_no = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )
    non_creamy_layer_date = models.DateField(
        null=True,
        blank=True
    )
    certificate_given_by = models.PositiveSmallIntegerField(
        choices=CertificateGivenByTypes.choices,
        default=None,
    )

    class Meta:
        db_table = 'profiles'
        verbose_name_plural = "Profiles"

    def __str__(self):
        if self.first_name and self.surname:
            return str(self.first_name) + str(self.surname)
        return self.id

profiles/forms/contacts.py
from django import forms

from profiles.models import Profile, ContactDetails
from django.forms.models import inlineformset_factory


class ContactDetailsForm(forms.ModelForm):

    class Meta:
        model = ContactDetails
        fields = ("address", "state", "district", "taluka", "mobile_no", "email")

        # widgets = {
        #     'address': forms.TextInput(attrs={'class': 'form-control'}),
        #     'state': forms.Select(attrs={'class': 'form-control select2'}),
        #     'district': forms.Select(attrs={'class': 'form-control select2'}),
        #     'taluka': forms.Select(attrs={'class': 'form-control select2'}),
        #     'mobile_no': forms.NumberInput(attrs={'class': 'form-control'}),
        #     'email': forms.TextInput(attrs={'class': 'form-control'}),
        # }


ContactDetailsFormSet = inlineformset_factory(
        Profile,
        ContactDetails,
        form=ContactDetailsForm,
        extra=1,
        can_delete=True
    )

profiles/forms/documents.py
from django import forms

from profiles.models import Profile, ProfileDocuments
from django.forms.models import inlineformset_factory


class ProfileDocumentsForm(forms.ModelForm):

    class Meta:
        model = ProfileDocuments
        fields = ("user_image", "signature_image", "caste_certificate", "non_creamy_layer_certificate",
                  "ews_certificate")

        # widgets = {
        #     'degree': forms.Select(attrs={'class': 'form-control select2'}),
        #     'institute_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'board_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'percentage': forms.TextInput(attrs={'class': 'form-control'}),
        #     'passing_year': forms.NumberInput(attrs={'class': 'form-control'}),
        #     'trials': forms.NumberInput(attrs={'class': 'form-control'}),
        #     'document': forms.NumberInput(attrs={'class': 'form-control'}),
        # }


ProfileDocumentsFormSet = inlineformset_factory(
        Profile,
        ProfileDocuments,
        form=ProfileDocumentsForm,
        extra=1,
        can_delete=True
    )

profiles/forms/education.py
from django import forms

from profiles.models import EducationDetails


class EducationDetailsForm(forms.ModelForm):

    class Meta:
        model = EducationDetails
        fields = ("degree", "institute_name", "board_name", "percentage", "passing_year", "trials", "document")

        # widgets = {
        #     'degree': forms.Select(attrs={'class': 'form-control select2'}),
        #     'institute_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'board_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'percentage': forms.TextInput(attrs={'class': 'form-control'}),
        #     'passing_year': forms.NumberInput(attrs={'class': 'form-control'}),
        #     'trials': forms.NumberInput(attrs={'class': 'form-control'}),
        #     'document': forms.NumberInput(attrs={'class': 'form-control'}),
        # }

profiles/forms/profiles.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit

from profiles.models.profiles import Profile
from profiles.custom_formset_layout_object import *


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ("title", "surname", "first_name", "father_husband", "mother_name",
                  "gender", "date_of_birth", "marital_status", "category", "certificate_no", "certificate_issued_date",
                  "certificate_issued_from", "non_creamy_layer_no", "non_creamy_layer_date", "certificate_given_by")

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                # Field('subject'),
                # Field('owner'),
                Fieldset('Add Education Details',
                         Formset('education_details_form')),
                # Field('note'),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'save')),
            )
        )
        # widgets = {
        #     'title': forms.Select(attrs={'class': 'form-control select2'}),
        #     'surname': forms.TextInput(attrs={'class': 'form-control'}),
        #     'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'father_husband': forms.TextInput(attrs={'class': 'form-control'}),
        #     'mother_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'gender': forms.Select(attrs={'class': 'form-control select2'}),
        #     'date_of_birth': forms.TextInput(attrs={
        #         'class': 'form-control datetimepicker-input',
        #         'data-toggle': 'datetimepicker',
        #         'placeholder': 'Select Date'
        #     }),
        #
        #     'marital_status': forms.Select(attrs={'class': 'form-control select2'}),
        #     'category': forms.Select(attrs={'class': 'form-control select2'}),
        #     'certificate_no': forms.TextInput(attrs={'class': 'form-control'}),
        #     'certificate_issued_date': forms.TextInput(attrs={
        #         'class': 'form-control datetimepicker-input',
        #         'data-toggle': 'datetimepicker',
        #         'placeholder': 'Select Date'
        #     }),
        #
        #     'certificate_issued_from': forms.Select(attrs={'class': 'form-control select2'}),
        #     'non_creamy_layer_no': forms.TextInput(attrs={'class': 'form-control select2'}),
        #     'non_creamy_layer_date': forms.TextInput(attrs={
        #         'class': 'form-control datetimepicker-input',
        #         'data-toggle': 'datetimepicker',
        #         'placeholder': 'Select Date'
        #     }),
        #
        #     'certificate_given_by': forms.Select(attrs={'class': 'form-control select2'}),
        # }
        #
        # labels = {
        #     'title': "Title",
        #     'surname': "Surname",
        #     'first_name': "First Name",
        #     'father_husband': "Father/Husband Name",
        #     'mother_name': "Mother Name",
        #     'gender': "Gender",
        #     'date_of_birth': "Date of Birth",
        #     'marital_status': "Marital Status",
        #     'category': "Category",
        #     'certificate_no': "Certificate No",
        #     'certificate_issued_date': "Certificate Issued Date",
        #     'certificate_issued_from': "Certificate Issued From",
        #     'non_creamy_layer_no': "Non-Creamy Layer Certificate No",
        #     'non_creamy_layer_date': "Non-Creamy Layer Certificate Issued Date",
        #     'certificate_given_by': "Certificate Given By",
        # }

profiles/views.py
from datetime import datetime

from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import render, redirect, get_object_or_404

from profiles.models import Profile
from profiles.utils import unique_id_generator
from profiles.forms import ProfileForm, ContactDetailsForm, EducationDetailsFormSet, ProfileDocumentsForm


class CreateProfileView(CreateView):
    model = Profile
    template_name = 'Profiles/profile_management.html'
    form_class = ProfileForm
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(CreateProfileView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['contact_details_form'] = ContactDetailsForm(self.request.POST)
            data['education_details_form'] = EducationDetailsFormSet(self.request.POST)
            data['documents_form'] = ProfileDocumentsForm(self.request.POST)
        else:
            data['contact_details_form'] = ContactDetailsForm()
            data['education_details_form'] = EducationDetailsFormSet()
            data['documents_form'] = ProfileDocumentsForm()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        contact_details = context['contact_details_form']
        education_details = context['education_details_form']
        documents_details = context['documents_form']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            form.instance.user = self.request.user
            form.instance.unique_id = unique_id_generator()
            self.object = form.save()

            if contact_details.is_valid():
                contact_details.instance.profile = self.object
                contact_details.save()

            if education_details.is_valid():
                education_details.instance = self.object
                education_details.save()

            if documents_details.is_valid():
                documents_details.instance.profile = self.object
                documents_details.save()

        return super(CreateProfileView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('dashboard')


# def manage_profile(request, uid=None):
#     context = {}
#
#     ContactDetails_InlineForm = inlineformset_factory(Profile, ContactDetails, form=ContactDetailsForm,
#                                                       fk_name='profile', extra=1)
#
#     if uid:
#         profile = get_object_or_404(Profile, pk=uid)
#         profile_contact_details = profile.contactdetails_set.all()
#
#         context.update({
#             'profile': profile,
#             'profile_contact_details': profile_contact_details
#         })
#     else:
#         profile = Profile()
#
#     # Form-Sets
#     contact_details_formset = ContactDetails_InlineForm(instance=profile)
#
#     if request.method == "POST":
#         form = ProfileForm(request.POST)
#
#         if uid:
#             form = ProfileForm(request.POST, instance=profile)
#
#         # Form-Sets
#         contact_details_formset = ContactDetails_InlineForm(request.POST, request.FILES)
#
#         if form.is_valid():
#             profile_object = form.save(commit=False)
#
#             contact_details_formset = ContactDetails_InlineForm(request.POST, request.FILES,
#                                                                         instance=profile_object, extra=0)
#
#             if not uid:
#                 profile_object.created_by = request.user
#
#             profile_object.updated_by = request.user
#             profile_object.updated_at = datetime.now()
#
#             if contact_details_formset.is_valid():
#                 profile_object.save()
#                 contact_details_formset.save()
#
#                 return redirect('/')
#     else:
#         if uid:
#             form = ProfileForm(instance=profile)
#         else:
#             form = ProfileForm()
#     context.update({
#         'form': form,
#         'contact_details_formset': contact_details_formset,
#     })
#
#     return render(request, 'Profiles/profile_management.html', context=context)

templates/Profiles/profile_management.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %}
    Profile Management
{% endblock %}


{% block extra_css %}

{% endblock %}


{% block content_header %}

{% endblock %}


{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                Create Profile
            </div>
            <div class="card-body">
                 {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}


{% block extra_js %}
    <script>
        function show_hide_options(){
            if ($('#id_category').val() === '1') {
                $('label[for="id_certificate_no"]').parent().hide();
                $('label[for="id_certificate_issued_date"]').parent().hide();
                $('label[for="id_certificate_issued_from"]').parent().hide();
                $('label[for="id_non_creamy_layer_no"]').parent().hide();
                $('label[for="id_non_creamy_layer_date"]').parent().hide();
                $('label[for="id_certificate_given_by"]').parent().hide();
            } else if ($('#id_category').val() === '2'){
                $('label[for="id_certificate_no"]').parent().show();
                $('label[for="id_certificate_issued_date"]').parent().show();
                $('label[for="id_certificate_issued_from"]').parent().hide();
                $('label[for="id_non_creamy_layer_no"]').parent().hide();
                $('label[for="id_non_creamy_layer_date"]').parent().hide();
                $('label[for="id_certificate_given_by"]').parent().show();
            } else  if ($('#id_category').val() === '3' ){
                $('label[for="id_certificate_no"]').parent().show();
                $('label[for="id_certificate_issued_date"]').parent().show();
                $('label[for="id_certificate_issued_from"]').parent().show();
                $('label[for="id_non_creamy_layer_no"]').parent().hide();
                $('label[for="id_non_creamy_layer_date"]').parent().hide();
                $('label[for="id_certificate_given_by"]').parent().hide();
            } else if ($('#id_category').val() === '4') {
                $('label[for="id_certificate_no"]').parent().show();
                $('label[for="id_certificate_issued_date"]').parent().show();
                $('label[for="id_certificate_issued_from"]').parent().show();
                $('label[for="id_non_creamy_layer_no"]').parent().show();
                $('label[for="id_non_creamy_layer_date"]').parent().show();
                $('label[for="id_certificate_given_by"]').parent().show();
            } else  if ($('#id_category').val() === '5' ) {
                $('label[for="id_certificate_no"]').parent().show();
                $('label[for="id_certificate_issued_date"]').parent().show();
                $('label[for="id_certificate_issued_from"]').parent().show();
                $('label[for="id_non_creamy_layer_no"]').parent().hide();
                $('label[for="id_non_creamy_layer_date"]').parent().hide();
                $('label[for="id_certificate_given_by"]').parent().hide();
            }
        }
        $(document).ready(function () {
            $(document).on('submit', 'form', function (e) {
                $(this).find('button').attr('disabled', 'disabled');
            });
            show_hide_options();
        });
        $(document).on('change', '#id_category', function (e) {
            show_hide_options();
        });

    </script>

    <!-- jQuery -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script type="application/javascript" src="{% static 'js/jquery.formset.js' %}"></script>

    <script>
        $('.contact_details_formset_row').formset({
            {#addText: 'Add Skill',#}
            {#addCssClass: 'btn btn-primary',#}
            {#deleteCssClass: 'btn btn-danger fa fa-trash bg-red formset-delete-btn',#}
            {#deleteText: '',#}
            {#prefix: 'skills_set',#}
            {#formCssClass: 'skill-inline-form',#}
        });
    </script>

    <script>
        function formatRepo(repo) {
            if (repo.loading) {
                return repo.text;
            }

            var $container = $(
                "<div class='select2-result-repository clearfix'>" +
                "<div class='select2-result-repository__avatar'><img src='" + repo.logo + "' /></div>" +
                "<div class='select2-result-repository__meta'>" +
                "<div class='select2-result-repository__title'></div>" +
                "<div class='select2-result-repository__description'></div>" +
                "</div>" +
                "</div>"
            );

            $container.find(".select2-result-repository__title").text(repo.text);
            $container.find(".select2-result-repository__description").text(repo.linkedin_url);

            return $container;
        }

        $(document).ready(function () {
            $(document).on('submit', 'form', function (e) {
                $(this).find('button').attr('disabled', 'disabled');
            });

            $('.datetimepicker-input').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: false,
                buttons: {
                    showClear: true
                }
            });

        });

        $(document).on('click', '.add-new-button', function (e) {
            e.preventDefault();
            var add_button = $(this);
            var field_name = add_button.data('name');
            var form_block = add_button.data('form-block');
            var total_forms_field = $('#' + form_block + '-TOTAL-FORMS')
            var total_forms = total_forms_field.val();
            var new_form_count = parseInt(total_forms) + 1;
            var new_form_count_string = '-' + new_form_count.toString();

            $('#' + form_block + ' .select-ajax').select2('destroy');
            $('#' + form_block + ' .select-firm-details').select2('destroy');
            $('#' + form_block + ' .select-simple').select2('destroy');
            var new_added_form = $('.' + form_block + ':last').clone().appendTo('#' + form_block);
            new_added_form.attr('id', form_block + new_form_count_string);
            new_added_form.find('textarea, input, select').each(function () {
                var curr_field = $(this);
                curr_field.attr('id', curr_field.data('field-name') + new_form_count_string);
                if (field_name === 1 && $(this).attr('type') !== "hidden"){
                    curr_field.attr('name', curr_field.data('field-name') + new_form_count_string);
                }
                curr_field.val('');
            });
            new_added_form.find('#firm-counter-id' + new_form_count_string).val(new_form_count);
            new_added_form.find('.firm-formset-label').html("#" + new_form_count);
            init_select2($('#' + form_block + ' .select-ajax'));
            init_industry_select2($('#' + form_block + ' .select-firm-details'));
            $('#' + form_block + ' .select-simple').select2();

            $('.' + form_block).not('#' + form_block + new_form_count_string).each(function () {
                $(this).find('.add-new-button').addClass('remove-form-button').addClass('fa-trash').addClass('btn-danger')
                    .removeClass('fa-plus').removeClass('add-new-button').removeClass('btn-primary')
                    .attr('id', form_block + '-REMOVE-BTN' + new_form_count_string);
            });

            total_forms_field.val(new_form_count);
        });

        $(document).on('click', '.remove-form-button', function (e) {
            e.preventDefault();
            var remove_button = $(this);
            var form_block = remove_button.data('form-block');
            var total_forms_field = $('#' + form_block + '-TOTAL-FORMS');
            var total_forms = total_forms_field.val();
            var new_form_count = parseInt(total_forms) - 1;

            remove_button.closest('.' + form_block).remove();
            {#total_forms_field.val(new_form_count);#}
        });

    </script>

{% endblock %}